import {
  FiCode,
  FiDatabase,
  FiGrid,
  FiLink,
  FiMonitor,
  FiServer,
  FiSmartphone,
  FiTool,
} from 'react-icons/fi'
import {
  SiC,
  SiCplusplus,
  SiDart,
  SiFastapi,
  SiFlask,
  SiFlutter,
  SiGit,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiMysql,
  SiNodedotjs,
  SiOpenjdk,
  SiPython,
  SiReact,
  SiSqlite,
  SiTailwindcss,
  SiVite,
} from 'react-icons/si'

export const skillIconMap = {
  api: FiLink,
  c: SiC,
  code: FiCode,
  cplusplus: SiCplusplus,
  css: FiCode,
  dart: SiDart,
  database: FiDatabase,
  fastapi: SiFastapi,
  flask: SiFlask,
  flutter: SiFlutter,
  git: SiGit,
  github: SiGithub,
  html: SiHtml5,
  java: SiOpenjdk,
  javascript: SiJavascript,
  layout: FiGrid,
  mobile: FiSmartphone,
  mongodb: SiMongodb,
  mysql: SiMysql,
  node: SiNodedotjs,
  python: SiPython,
  react: SiReact,
  responsive: FiMonitor,
  server: FiServer,
  sqlite: SiSqlite,
  tailwind: SiTailwindcss,
  tools: FiTool,
  vite: SiVite,
  vscode: FiMonitor,
  web: FiMonitor,
}

export function getSkillIcon(iconKey) {
  return skillIconMap[iconKey] ?? FiCode
}
